In [4]:
import numpy as np

def LR(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    U = A.copy()
    P = np.eye(n)
    
    for i in range(n):
        # Pivotisierung (Zeilenvertauschung)
        max_row = np.argmax(abs(U[i:, i])) + i
        if i != max_row:
            U[[i, max_row], :] = U[[max_row, i], :]
            P[[i, max_row], :] = P[[max_row, i], :]
            if i > 0:
                L[[i, max_row], :i] = L[[max_row, i], :i]
        
        # Berechnung von L und U
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j, :] -= L[j, i] * U[i, :]
    
    np.fill_diagonal(L, 1)
    
    return L, U, P

# Beispiel zur Überprüfung
A = np.array([
    [9, -2, 1, -0.5],
    [-1.5, 30, -12, 0],
    [1, -15, 0, -4],
    [0, -6, 18, 8]
])

L, U, P = LR(A)
print("L:\n", L)
print("U:\n", U)
print("P:\n", P)



L:
 [[ 1.          0.          0.          0.        ]
 [-0.16666667  1.          0.          0.        ]
 [ 0.         -0.20224719  1.          0.        ]
 [ 0.11111111 -0.49812734 -0.38480922  1.        ]]
U:
 [[  9.          -2.           1.          -0.5       ]
 [  0.          29.66666667 -11.83333333  -0.08333333]
 [  0.           0.          15.60674157   7.98314607]
 [  0.           0.           0.          -0.91396688]]
P:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [8]:
def solve_system(A, b):
    L, U, P = LR(A)
    n = A.shape[0]
    
    # Schritt 1: Ly = Pb lösen
    Pb = np.dot(P, b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = Pb[i] - np.dot(L[i, :i], y[:i])
    
    # Schritt 2: Ux = y lösen
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]
    
    return x

# Gegebenes Gleichungssystem
A = np.array([
    [9, -2, 1, -0.5],
    [-1.5, 30, -12, 0],
    [1, -15, 0, -4],
    [0, -6, 18, 8]
])
b = np.array([3, 3, 2, -4])

# Lösung des Gleichungssystems
x = solve_system(A, b)
print("Lösung x:", x)


Lösung x: [ 0.20559275  0.50571091  0.98857818 -2.34501772]
