In [7]:
import numpy as np

# Gegebene Matrizen und Vektoren
A = np.array([[1, 1, 1],
              [1, 1, 3],
              [1, 3, 1],
              [1, 3, 3]])
b = np.array([3, 1, 3, 3])

# Berechnung der Normalengleichung
AtA = np.dot(A.T, A)
Atb = np.dot(A.T, b)

# Cholesky-Zerlegung
L = np.linalg.cholesky(AtA)

# Lösung des linearen Gleichungssystems
y = np.linalg.solve(L, Atb)
x_cholesky = np.linalg.solve(L.T, y)

print("Cholesky-Zerlegung L:\n", L)
print("Lösung x (Cholesky):\n", x_cholesky)

# Überprüfung der Lösung
Ax = np.dot(A, x_cholesky)
print("Ax:\n", Ax)
print("b:\n", b)
print("Fehler (Ax - b):\n", Ax - b)


Cholesky-Zerlegung L:
 [[2. 0. 0.]
 [4. 2. 0.]
 [4. 0. 2.]]
Lösung x (Cholesky):
 [ 2.5  0.5 -0.5]
Ax:
 [2.5 1.5 3.5 2.5]
b:
 [3 1 3 3]
Fehler (Ax - b):
 [-0.5  0.5  0.5 -0.5]


In [8]:
# Funktion zur QR-Zerlegung mit Householder-Transformation
def householder_qr(A):
    m, n = A.shape
    R = A.copy()
    V = np.zeros((m, n))

    for k in range(n):
        x = R[k:m, k]
        e1 = np.zeros_like(x)
        e1[0] = 1
        v_k = np.sign(x[0]) * np.linalg.norm(x) * e1 + x
        v_k /= np.linalg.norm(v_k)
        V[k:m, k] = v_k
        R[k:m, k:n] -= 2 * np.outer(v_k, np.dot(v_k, R[k:m, k:n]))
    
    return V, R

def form_Q(V):
    m, n = V.shape
    Q = np.eye(m)
    
    for k in range(n-1, -1, -1):
        v_k = V[k:m, k]
        H_k = np.eye(m)
        H_k[k:m, k:m] -= 2 * np.outer(v_k, v_k)
        Q = np.dot(H_k, Q)
    
    return Q

# QR-Zerlegung der Matrix A
V, R = householder_qr(A)

# Berechnung von Q
Q = form_Q(V)

# Lösung des linearen Ausgleichsproblems
Q_T_b = np.dot(Q.T, b)
x_qr = np.linalg.solve(R[:3, :3], Q_T_b[:3])

print("V (Householder-Vektoren):\n", V)
print("R (obere Dreiecksmatrix):\n", R)
print("Q (orthogonale Matrix):\n", Q)
print("Lösung x (QR):\n", x_qr)

# Überprüfung der Lösung
Ax = np.dot(A, x_qr)
print("Ax:\n", Ax)
print("b:\n", b)
print("Fehler (Ax - b):\n", Ax - b)


UFuncTypeError: Cannot cast ufunc 'subtract' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'